---
# tasks file for itspirit.bootstrap

- name: Update all packages to the latest version.
  apt:
    upgrade: safe
    update_cache: yes
    cache_valid_time: 3600


- name: Ensure acl filesystem support is available.
  apt:
    pkg: acl
    state: present


- name: Ensure system administrators are set up.
  user:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    shell: '{{ item.shell | default("/bin/bash") }}'
    password: '{{ item.password | default("") }}'
  with_items: '{{ sysadmins }}'
  no_log: true


- name: Ensure authorized keys for active system administrators are set up.
  authorized_key:
    user: '{{ item.name }}'
    key: '{{ item.ssh_key }}'
  when: '{{ item.state == "present" }}'
  with_items: '{{ sysadmins }}'
  no_log: true
